import { darkTheme, type GlobalTheme, type GlobalThemeOverrides } from 'naive-ui'

import type { ResolvedOneKVMTheme } from './types'

export function naiveThemeFor(theme: ResolvedOneKVMTheme): GlobalTheme | null {
  return theme.appearance === 'dark' ? darkTheme : null
}

export function naiveOverridesFor(theme: ResolvedOneKVMTheme): GlobalThemeOverrides {
  const token = theme.tokens
  return {
    common: {
      baseColor: token.background,
      primaryColor: token.primary,
      primaryColorHover: token.primaryHover,
      primaryColorPressed: token.primaryPressed,
      primaryColorSuppl: token.primaryHover,
      infoColor: token.primary,
      infoColorHover: token.primaryHover,
      infoColorPressed: token.primaryPressed,
      infoColorSuppl: token.primaryHover,
      successColor: token.success,
      successColorHover: token.success,
      successColorPressed: token.success,
      successColorSuppl: token.success,
      warningColor: token.warning,
      warningColorHover: token.warning,
      warningColorPressed: token.warning,
      warningColorSuppl: token.warning,
      errorColor: token.destructive,
      errorColorHover: token.destructiveHover,
      errorColorPressed: token.destructivePressed,
      errorColorSuppl: token.destructiveHover,
      textColorBase: token.foreground,
      textColor1: token.foreground,
      textColor2: token.textSecondary,
      textColor3: token.mutedForeground,
      textColorDisabled: token.mutedForeground,
      placeholderColor: token.mutedForeground,
      placeholderColorDisabled: token.mutedForeground,
      iconColor: token.mutedForeground,
      iconColorHover: token.foreground,
      iconColorPressed: token.foreground,
      iconColorDisabled: token.mutedForeground,
      dividerColor: token.border,
      borderColor: token.border,
      scrollbarColor: 'rgb(142 154 167 / 28%)',
      scrollbarColorHover: 'rgb(142 154 167 / 48%)',
      scrollbarBorderRadius: token.radius,
      progressRailColor: token.muted,
      railColor: token.muted,
      popoverColor: token.popover,
      tableColor: token.card,
      cardColor: token.card,
      modalColor: token.card,
      bodyColor: token.background,
      tagColor: token.secondary,
      avatarColor: token.secondary,
      inputColor: token.input,
      codeColor: token.surfaceInset,
      tabColor: token.secondary,
      actionColor: token.secondary,
      tableHeaderColor: token.muted,
      hoverColor: token.accent,
      tableColorHover: token.accent,
      tableColorStriped: token.muted,
      pressedColor: token.secondaryHover,
      inputColorDisabled: token.muted,
      buttonColor2: token.secondary,
      buttonColor2Hover: token.secondaryHover,
      buttonColor2Pressed: token.accent,
      boxShadow1: token.shadowPanel,
      boxShadow2: token.shadowPopover,
      boxShadow3: token.shadowPopover,
      fontFamily: 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      fontFamilyMono: 'ui-monospace, "SFMono-Regular", Menlo, Monaco, Consolas, "Liberation Mono", monospace',
      fontWeight: '400',
      fontWeightStrong: '600',
      cubicBezierEaseInOut: 'cubic-bezier(0.65, 0, 0.35, 1)',
      cubicBezierEaseOut: 'cubic-bezier(0.23, 1, 0.32, 1)',
      cubicBezierEaseIn: 'cubic-bezier(0.77, 0, 0.175, 1)',
      borderRadius: token.radius,
      borderRadiusSmall: token.radiusSmall,
      heightSmall: '32px',
      heightMedium: '36px',
      heightLarge: '40px',
      fontSize: '14px',
      fontSizeSmall: '13px',
      fontSizeMedium: '14px',
      lineHeight: '1.45',
    },
    Button: {
      borderRadiusTiny: token.radiusSmall,
      borderRadiusSmall: token.radius,
      borderRadiusMedium: token.radius,
      borderRadiusLarge: token.radiusLarge,
      fontWeight: '500',
      fontWeightStrong: '600',
      color: token.secondary,
      colorHover: token.secondaryHover,
      colorPressed: token.accent,
      colorFocus: token.secondaryHover,
      textColor: token.secondaryForeground,
      textColorHover: token.foreground,
      textColorPressed: token.foreground,
      textColorFocus: token.foreground,
      border: `1px solid ${token.border}`,
      borderHover: `1px solid ${token.borderStrong}`,
      borderPressed: `1px solid ${token.borderStrong}`,
      borderFocus: `1px solid ${token.ring}`,
      colorPrimary: token.primary,
      colorHoverPrimary: token.primaryHover,
      colorPressedPrimary: token.primaryPressed,
      colorFocusPrimary: token.primary,
      textColorPrimary: token.primaryForeground,
      textColorHoverPrimary: token.primaryForeground,
      textColorPressedPrimary: token.primaryForeground,
      textColorFocusPrimary: token.primaryForeground,
      borderPrimary: `1px solid ${token.primary}`,
      borderHoverPrimary: `1px solid ${token.primaryHover}`,
      borderPressedPrimary: `1px solid ${token.primaryPressed}`,
      borderFocusPrimary: `1px solid ${token.ring}`,
    },
    Input: {
      borderRadius: token.radius,
      color: token.input,
      colorFocus: token.input,
      textColor: token.foreground,
      placeholderColor: token.mutedForeground,
      border: `1px solid ${token.border}`,
      borderHover: `1px solid ${token.borderStrong}`,
      borderFocus: `1px solid ${token.ring}`,
      boxShadowFocus: `0 0 0 2px color-mix(in srgb, ${token.ring} 24%, transparent)`,
    },
    Popover: {
      borderRadius: token.radiusLarge,
      color: token.popover,
      dividerColor: token.border,
      textColor: token.popoverForeground,
      boxShadow: token.shadowPopover,
      padding: '12px',
    },
    Tooltip: {
      color: token.popover,
      textColor: token.popoverForeground,
      boxShadow: token.shadowPopover,
    },
    Dropdown: {
      color: token.popover,
      optionTextColor: token.foreground,
      optionTextColorHover: token.foreground,
      optionTextColorActive: token.primary,
      optionColorHover: token.accent,
      optionColorActive: `color-mix(in srgb, ${token.primary} 12%, ${token.card})`,
      groupHeaderTextColor: token.mutedForeground,
    },
    Menu: {
      itemTextColor: token.foreground,
      itemTextColorHover: token.foreground,
      itemTextColorActive: token.primary,
      itemTextColorActiveHover: token.primaryHover,
      itemColorActive: `color-mix(in srgb, ${token.primary} 12%, ${token.card})`,
      itemColorActiveHover: `color-mix(in srgb, ${token.primary} 16%, ${token.card})`,
      itemColorHover: token.accent,
      groupTextColor: token.mutedForeground,
      arrowColor: token.mutedForeground,
    },
    Modal: {
      color: token.card,
      textColor: token.cardForeground,
      boxShadow: token.shadowPopover,
    },
    Drawer: {
      borderRadius: '0px',
      color: token.card,
      textColor: token.cardForeground,
      titleTextColor: token.foreground,
      boxShadow: token.shadowPopover,
      headerBorderBottom: `1px solid ${token.border}`,
      footerBorderTop: `1px solid ${token.border}`,
    },
    Card: {
      borderRadius: token.radiusLarge,
      color: token.card,
      textColor: token.cardForeground,
      titleTextColor: token.foreground,
      borderColor: token.border,
      boxShadow: 'none',
    },
    Select: {
      menuBoxShadow: token.shadowPopover,
    },
    InternalSelection: {
      borderRadius: token.radius,
      color: token.input,
      colorActive: token.input,
      textColor: token.foreground,
      placeholderColor: token.mutedForeground,
      border: `1px solid ${token.border}`,
      borderHover: `1px solid ${token.borderStrong}`,
      borderActive: `1px solid ${token.ring}`,
      borderFocus: `1px solid ${token.ring}`,
      boxShadowHover: 'none',
      boxShadowActive: `0 0 0 2px color-mix(in srgb, ${token.ring} 24%, transparent)`,
      boxShadowFocus: `0 0 0 2px color-mix(in srgb, ${token.ring} 24%, transparent)`,
      arrowColor: token.mutedForeground,
    },
  }
}
